// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeStore.Data;

namespace ShoeStore.Migrations.ShoeStoreDb
{
    [DbContext(typeof(ShoeStoreDbContext))]
    partial class ShoeStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ShoeStore.Models.Shoe", b =>
                {
                    b.Property<int>("ShoeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("shoeId");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("money");

                    b.Property<byte[]>("ShoeImage")
                        .HasColumnName("shoeImage");

                    b.Property<string>("ShoeName")
                        .HasColumnName("shoeName")
                        .HasMaxLength(50);

                    b.HasKey("ShoeId");

                    b.ToTable("Shoe");
                });

            modelBuilder.Entity("ShoeStore.Models.UserCart", b =>
                {
                    b.Property<int>("ShoeId")
                        .HasColumnName("shoeId");

                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("cartId");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<int>("Quantity")
                        .HasColumnName("quantity");

                    b.HasKey("ShoeId", "CartId");

                    b.ToTable("UserCart");
                });

            modelBuilder.Entity("ShoeStore.Models.UserCart", b =>
                {
                    b.HasOne("ShoeStore.Models.Shoe", "Shoe")
                        .WithMany("UserCart")
                        .HasForeignKey("ShoeId")
                        .HasConstraintName("FK__UserCart");
                });
#pragma warning restore 612, 618
        }
    }
}
